name: Publish Live Website

on:
  push:
    branches:
      - live

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.149.0'
          extended: true

      - name: Build Site
        run: hugo --minify

      - name: Configure Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.LIVE_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.LIVE_AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Deploy Site
        run: hugo deploy
